_base_ = ['./goldmdd_mcpnet_full_80ep_bs8.py']

norm_cfg = dict(type='BN', requires_grad=True)

model = dict(
    decode_head=[
        dict(
            type='RefineASPPHead',
            in_channels=2048,
            in_index=3,
            channels=128,
            dilations=(1, 12, 24, 36),
            dropout_ratio=0.1,
            num_classes=14,
            norm_cfg=norm_cfg,
            align_corners=False,
            loss_decode=[
                dict(
                    type='FocalLoss',
                    use_sigmoid=True,
                    gamma=2.0,
                    alpha=0.5,
                    loss_weight=1.0,
                    loss_name='loss_focal',
                ),
                dict(
                    type='DiceLoss',
                    use_sigmoid=False,
                    activate=True,
                    ignore_index=255,
                    naive_dice=False,
                    eps=1e-3,
                    loss_weight=1.0,
                    loss_name='loss_dice',
                ),
            ],
        ),
        dict(
            type='ISDHead',
            in_channels=3,
            prev_channels=128,
            down_ratio=4,
            channels=128,
            num_classes=14,
            dropout_ratio=0.1,
            fusion_mode='raf',
            model_cls='ShallowNet',
            dims=[12, 24, 48, 96],
            depths=[1, 1, 2, 1],
            shallow_model_inchan=3,
            lap=False,
            consist=False,
            norm_cfg=norm_cfg,
            align_corners=False,
            loss_decode=[
                dict(
                    type='FocalLoss',
                    use_sigmoid=True,
                    gamma=2.0,
                    alpha=0.5,
                    loss_weight=1.0,
                    loss_name='loss_focal',
                ),
                dict(
                    type='DiceLoss',
                    use_sigmoid=False,
                    activate=True,
                    ignore_index=255,
                    naive_dice=False,
                    eps=1e-3,
                    loss_weight=1.0,
                    loss_name='loss_dice',
                ),
            ],
        ),
    ],
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=14,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.5,
            loss_weight=0.4,
            loss_name='loss_aux_focal',
        ),
    ),
)

